### PR TITLE
mac 11 ARM: starting to translate Daniel's build instructions

### PR DESCRIPTION
**Pull request by mrneont**

### CODE REVIEW

**Comment by mrneont** [comment]
Thanks, @afni-dglen :  could you please review the notes and check lots of things I commented on?  There were some details missing that I put **Question:** items about.

**Comment by afni-dglen** [comment]
Some of the questions are answered in building notes. I'll try to answer some that are addressed:

netpbm and libiconv should be added to the brew install - together with the rest of the brew installation steps.

Only one symbolic link remains to be included.

The name of the base Makefile and the output should be simplified but should include ARM in the name for this documentation. We can discuss or just go with the simpler name you suggest. I added another Makefile  to the repository that's the latest, to reflect the testing platforms. I believe these will work with earlier MacOS 11 versions (11.x)  and later ones for Monterey (12.x) too.  I expect the Intel64 should follow this setup closely with the exception that homebrew will likely go into /usr/local instead of /opt/homebrew.

The verification step is the typical afni_system_check.py.

I have tested for both the clang (Apple's gcc) and for recent gcc versions provided by homebrew (versions 10, 11). Both work, but we can provide a single version guidance here to make it easier for the user. The notes document was meant primarily for developers, where the choices are more welcome.

Similarly, atlases can just go in the abin or installed name directory, but we can consider another atlas path if needed. The single directory guidance will be preferred for user instructions.

**Comment by mrneont** [comment]
Hi, @afni-dglen : it would be great if you could make the changes or commented on the questions directly in the files here:
https://github.com/afni/afni_doc/pull/4/files
That level of specificity would be useful.

**Comment by afni-dglen** [comment]
OK, updated  the notes in the source branch and the rst here. The path variables are still an outstanding issue.

**Comment by mrneont** [comment]
Outstanding, indeed (the notes you updated, that is)!

**Comment by mrneont** [comment]
This branch---with installation instructions for macOS 11---appears to be greatly superseded by modern instructions, and so I am closing this pull request.

**Pull request closed without merging**
